name: generator

issues:
  types: [opened, labeled]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: generate blog post
        uses: ./
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
